<?xml version="1.0" encoding="utf-8"?>
<!--
** This is a template build file for a JOSM  plugin.
**
** Maintaining versions
** ====================
** See README.template
**
** Usage
** =====
** Call "ant help" to get possible build targets.
**
-->
<project name="WebsiteWizard" default="dist" basedir=".">

    <!-- enter the SVN commit message -->
    <property name="commit.message" value="Add WebsiteWizard plugin"/>
    <!-- enter the *lowest* JOSM version this plugin is currently compatible with -->
    <property name="plugin.main.version" value="19613"/>

    <!-- Configure these properties (replace "..." accordingly).
         See https://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins
    -->
    <property name="plugin.author" value="goliath_jr"/>
    <property name="plugin.class" value="org.openstreetmap.josm.plugins.websitewizard.WebsiteWizardPlugin"/>
    <property name="plugin.description" value="Add website tag to places as easily as possible."/>
    <property name="plugin.icon" value="images/websitewizard.svg"/>
    <property name="plugin.link" value="https://github.com/High5Apps/josm-plugin-website-wizard"/>
    <property name="plugin.canloadatruntime" value="true"/>
    <property name="plugin.version" value="1.0.0"/>

    <!-- ** include targets that all plugins have in common ** -->
    <import file="../build-common.xml"/>
  
</project>
